name: pyinstaller
on: workflow_dispatch

jobs:
  build-in-env:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v3
      - name: show ENV 
        run: env
      - name: print env
        run: echo $GITHUB_REPOSITORY
  # build-on-windows:
  #   runs-on: windows-2022
  #   steps: 
  #     - name: checkout code
  #       uses: actions/checkout@v3
  #     - name: install pyinstaller
  #       run: pip install pyinstaller
  #     - name: build exe
  #       run: pyinstaller sha256.py -F 
  #     - name: upload exe file
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: sha256-windows-exe
  #         path: dist/sha256.exe

  # test-build-windows:
  #   runs-on: windows-2022
  #   needs: build-on-windows
  #   steps:
  #     - name: download exe file
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: sha256-windows-exe
  #     - name: test exe file
  #       run: |
  #         ls
  #         ./sha256.exe sha256.exe